DEMO_SCENARIOS = {
    "safe_listing": {
        "listing_id": "L-SAFE-001",
        "name": "Safe Listing",
        "expected_risk": "LOW",
        "expected_action": "ALLOW",
        "versions": [
            {
                "listing_id": "L-SAFE-001",
                "version": 1,
                "status": "approved",
                "title": "Uniqlo Airism Cotton T-Shirt",
                "description": "Lightly used. Bought from Uniqlo Singapore.",
                "brand": "Uniqlo",
                "price": 12,
                "image_id": "uniqlo_tshirt_clear_photo",
                "seller_id": "S-SAFE",
            },
            {
                "listing_id": "L-SAFE-001",
                "version": 2,
                "status": "approved",
                "title": "Uniqlo AIRism Cotton T-Shirt",
                "description": "Lightly used. Bought from Uniqlo Singapore. Washed once.",
                "brand": "Uniqlo",
                "price": 11,
                "image_id": "uniqlo_tshirt_clear_photo_v2",
                "seller_id": "S-SAFE",
            },
        ],
    },
    "brand_injection": {
        "listing_id": "L-BRAND-001",
        "name": "Brand Injection",
        "expected_risk": "CRITICAL",
        "expected_action": "TEMPORARY_SUPPRESSION_AND_HUMAN_REVIEW",
        "versions": [
            {
                "listing_id": "L-BRAND-001",
                "version": 1,
                "status": "approved",
                "title": "Wireless Earbuds Bluetooth 5.0",
                "description": "Good condition wireless earbuds.",
                "brand": None,
                "price": 30,
                "image_id": "generic_earbuds_01",
                "seller_id": "S-RISKY-001",
            },
            {
                "listing_id": "L-BRAND-001",
                "version": 2,
                "status": "approved",
                "title": "Apple AirPods Pro OEM 1:1 Authentic",
                "description": "Factory batch, same production line, mirror quality.",
                "brand": "Apple",
                "price": 12,
                "image_id": "airpods_branded_box_01",
                "seller_id": "S-RISKY-001",
            },
        ],
    },
    "replica_reveal": {
        "listing_id": "L-REPLICA-001",
        "name": "Replica Reveal",
        "expected_risk": "CRITICAL",
        "expected_action": "TEMPORARY_SUPPRESSION_AND_HUMAN_REVIEW",
        "versions": [
            {
                "listing_id": "L-REPLICA-001",
                "version": 1,
                "status": "approved",
                "title": "Premium Leather Handbag",
                "description": "Stylish leather handbag.",
                "brand": None,
                "price": 180,
                "image_id": "generic_handbag_01",
                "seller_id": "S-RISKY-002",
            },
            {
                "listing_id": "L-REPLICA-001",
                "version": 2,
                "status": "approved",
                "title": "Luxury Designer Bag 1:1 Mirror Quality AAA",
                "description": "Original quality, factory direct, no receipt.",
                "brand": "Luxury Designer",
                "price": 39,
                "image_id": "designer_bag_packaging_01",
                "seller_id": "S-RISKY-002",
            },
        ],
    },
    "legitimate_edit": {
        "listing_id": "L-LEGIT-001",
        "name": "Legitimate Edit",
        "expected_risk": "LOW",
        "expected_action": "ALLOW",
        "versions": [
            {
                "listing_id": "L-LEGIT-001",
                "version": 1,
                "status": "approved",
                "title": "Nike Running Shoes Size 9",
                "description": "Used pair, authentic, normal wear.",
                "brand": "Nike",
                "price": 70,
                "image_id": "nike_shoes_photo_blurry",
                "seller_id": "S-LEGIT-001",
            },
            {
                "listing_id": "L-LEGIT-001",
                "version": 2,
                "status": "approved",
                "title": "Nike Running Shoes Size US 9",
                "description": "Used pair, authentic, normal wear. Added clearer photo.",
                "brand": "Nike",
                "price": 68,
                "image_id": "nike_shoes_photo_clear",
                "seller_id": "S-LEGIT-001",
            },
        ],
    },
    "image_only_suspicious": {
        "listing_id": "L-IMAGE-001",
        "name": "Image-Only Suspicious Edit",
        "expected_risk": "MEDIUM",
        "expected_action": "MONITOR",
        "versions": [
            {
                "listing_id": "L-IMAGE-001",
                "version": 1,
                "status": "approved",
                "title": "Sports Shoes",
                "description": "Comfortable running shoes.",
                "brand": None,
                "price": 45,
                "image_id": "generic_shoes_01",
                "seller_id": "S-IMAGE-001",
            },
            {
                "listing_id": "L-IMAGE-001",
                "version": 2,
                "status": "approved",
                "title": "Sports Shoes",
                "description": "Comfortable running shoes.",
                "brand": None,
                "price": 45,
                "image_id": "branded_luxury_shoes_box_01",
                "seller_id": "S-IMAGE-001",
            },
        ],
    },
}
