PHASE2_SCENARIOS = {
    "baseline_safe_creation": {
        "listing_id": "L-BASE-SAFE-001",
        "name": "Baseline Safe Listing Creation",
        "expected": {"risk_level": "LOW", "recommended_action": "ALLOW"},
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Canvas Tote Bag",
                "description": "New canvas tote with inner pocket.",
                "brand": None,
                "price": 12,
                "image_id": "canvas_tote_01",
                "seller_id": "S-BASE-SAFE-001",
            }
        ],
        "seller_profile": {
            "seller_id": "S-BASE-SAFE-001",
            "seller_age_days": 720,
            "prior_flags": 0,
            "similar_listing_count_24h": 1,
        },
        "review_profile": {
            "avg_rating": 4.7,
            "review_count": 44,
            "generic_review_ratio": 0.14,
            "review_burst_detected": False,
        },
        "image_metadata": {
            "previous_image_id": None,
            "current_image_id": "canvas_tote_01",
            "image_changed": False,
            "contains_brand_logo": False,
            "contains_packaging": False,
            "image_category": "canvas_tote",
        },
    },
    "baseline_risky_creation": {
        "listing_id": "L-BASE-RISK-001",
        "name": "Baseline Risky Listing Creation",
        "expected": {"risk_level": "MEDIUM", "recommended_action": "MONITOR"},
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Luxury Designer Bag 1:1 Mirror Quality AAA",
                "description": "Original quality, factory direct, no receipt.",
                "brand": "Luxury Designer",
                "price": 39,
                "image_id": "designer_bag_packaging_01",
                "seller_id": "S-BASE-RISK-001",
            }
        ],
        "seller_profile": {
            "seller_id": "S-BASE-RISK-001",
            "seller_age_days": 8,
            "prior_flags": 3,
            "similar_listing_count_24h": 12,
        },
        "review_profile": {
            "avg_rating": 4.9,
            "review_count": 128,
            "generic_review_ratio": 0.72,
            "review_burst_detected": True,
        },
        "image_metadata": {
            "previous_image_id": None,
            "current_image_id": "designer_bag_packaging_01",
            "image_changed": False,
            "contains_brand_logo": True,
            "contains_packaging": True,
            "image_category": "luxury_bag_packaging",
        },
    },
    "legitimate_edit": {
        "listing_id": "L-LEGIT-001",
        "name": "Legitimate Edit",
        "expected": {"risk_level": "LOW", "recommended_action": "ALLOW"},
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Nike Running Shoes Size 9",
                "description": "Used pair, authentic, normal wear.",
                "brand": "Nike",
                "price": 70,
                "image_id": "nike_shoes_photo_blurry",
                "seller_id": "S-LEGIT-001",
            },
            {
                "version": 2,
                "status": "approved",
                "title": "Nike Running Shoes Size US 9",
                "description": "Used pair, authentic, normal wear. Added clearer photo.",
                "brand": "Nike",
                "price": 68,
                "image_id": "nike_shoes_photo_clear",
                "seller_id": "S-LEGIT-001",
            },
        ],
        "seller_profile": {
            "seller_id": "S-LEGIT-001",
            "seller_age_days": 900,
            "prior_flags": 0,
            "similar_listing_count_24h": 1,
        },
        "review_profile": {
            "avg_rating": 4.8,
            "review_count": 82,
            "generic_review_ratio": 0.12,
            "review_burst_detected": False,
        },
        "image_metadata": {
            "previous_image_id": "nike_shoes_photo_blurry",
            "current_image_id": "nike_shoes_photo_clear",
            "image_changed": True,
            "contains_brand_logo": False,
            "contains_packaging": False,
            "image_category": "running_shoes",
        },
    },
    "luxury_full_risk": {
        "listing_id": "L-LUX-001",
        "name": "Full Luxury Counterfeit Risk",
        "expected": {
            "risk_level": "CRITICAL",
            "recommended_action": "TEMPORARY_SUPPRESSION_AND_HUMAN_REVIEW",
        },
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Premium Leather Handbag",
                "description": "Stylish leather handbag in good condition.",
                "brand": None,
                "price": 180,
                "image_id": "generic_handbag_01",
                "seller_id": "S-RISKY-001",
            },
            {
                "version": 2,
                "status": "approved",
                "title": "Luxury Designer Bag 1:1 Mirror Quality AAA",
                "description": "Original quality, factory direct, no receipt.",
                "brand": "Luxury Designer",
                "price": 39,
                "image_id": "designer_bag_packaging_01",
                "seller_id": "S-RISKY-001",
            },
        ],
        "seller_profile": {
            "seller_id": "S-RISKY-001",
            "seller_age_days": 8,
            "prior_flags": 3,
            "similar_listing_count_24h": 12,
        },
        "review_profile": {
            "avg_rating": 4.9,
            "review_count": 128,
            "generic_review_ratio": 0.72,
            "review_burst_detected": True,
        },
        "image_metadata": {
            "previous_image_id": "generic_handbag_01",
            "current_image_id": "designer_bag_packaging_01",
            "image_changed": True,
            "contains_brand_logo": True,
            "contains_packaging": True,
            "image_category": "luxury_bag_packaging",
        },
    },
    "image_only_suspicious": {
        "listing_id": "L-IMAGE-001",
        "name": "Image-Only Suspicious Edit",
        "expected": {"risk_level": "MEDIUM", "recommended_action": "REQUEST_VERIFICATION"},
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Sports Shoes",
                "description": "Comfortable running shoes.",
                "brand": None,
                "price": 45,
                "image_id": "generic_shoes_01",
                "seller_id": "S-IMAGE-001",
            },
            {
                "version": 2,
                "status": "approved",
                "title": "Sports Shoes",
                "description": "Comfortable running shoes.",
                "brand": None,
                "price": 45,
                "image_id": "branded_luxury_shoes_box_01",
                "seller_id": "S-IMAGE-001",
            },
        ],
        "seller_profile": {
            "seller_id": "S-IMAGE-001",
            "seller_age_days": 120,
            "prior_flags": 0,
            "similar_listing_count_24h": 1,
        },
        "review_profile": {
            "avg_rating": 4.6,
            "review_count": 35,
            "generic_review_ratio": 0.18,
            "review_burst_detected": False,
        },
        "image_metadata": {
            "previous_image_id": "generic_shoes_01",
            "current_image_id": "branded_luxury_shoes_box_01",
            "image_changed": True,
            "contains_brand_logo": True,
            "contains_packaging": True,
            "image_category": "branded_shoes_packaging",
        },
    },
    "price_drop_only": {
        "listing_id": "L-PRICE-001",
        "name": "Price Drop Only",
        "expected": {"risk_level": "MEDIUM", "recommended_action": "MONITOR"},
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Leather Wallet",
                "description": "Used leather wallet in good condition.",
                "brand": None,
                "price": 120,
                "image_id": "wallet_photo_01",
                "seller_id": "S-PRICE-001",
            },
            {
                "version": 2,
                "status": "approved",
                "title": "Leather Wallet",
                "description": "Used leather wallet in good condition. Clearance sale.",
                "brand": None,
                "price": 45,
                "image_id": "wallet_photo_01",
                "seller_id": "S-PRICE-001",
            },
        ],
        "seller_profile": {
            "seller_id": "S-PRICE-001",
            "seller_age_days": 600,
            "prior_flags": 0,
            "similar_listing_count_24h": 1,
        },
        "review_profile": {
            "avg_rating": 4.7,
            "review_count": 50,
            "generic_review_ratio": 0.2,
            "review_burst_detected": False,
        },
        "image_metadata": {
            "previous_image_id": "wallet_photo_01",
            "current_image_id": "wallet_photo_01",
            "image_changed": False,
            "contains_brand_logo": False,
            "contains_packaging": False,
            "image_category": "wallet",
        },
    },
    "review_abuse": {
        "listing_id": "L-REVIEW-001",
        "name": "Review Abuse",
        "expected": {"risk_level": "MEDIUM", "recommended_action": "MONITOR"},
        "timeline": [
            {
                "version": 1,
                "status": "approved",
                "title": "Luxury Watch Strap",
                "description": "Watch strap compatible with many watches.",
                "brand": None,
                "price": 35,
                "image_id": "watch_strap_01",
                "seller_id": "S-REVIEW-001",
            },
            {
                "version": 2,
                "status": "approved",
                "title": "Luxury Watch Strap",
                "description": "Watch strap compatible with many watches.",
                "brand": None,
                "price": 35,
                "image_id": "watch_strap_01",
                "seller_id": "S-REVIEW-001",
            },
        ],
        "seller_profile": {
            "seller_id": "S-REVIEW-001",
            "seller_age_days": 20,
            "prior_flags": 1,
            "similar_listing_count_24h": 9,
        },
        "review_profile": {
            "avg_rating": 5.0,
            "review_count": 220,
            "generic_review_ratio": 0.83,
            "review_burst_detected": True,
        },
        "image_metadata": {
            "previous_image_id": "watch_strap_01",
            "current_image_id": "watch_strap_01",
            "image_changed": False,
            "contains_brand_logo": False,
            "contains_packaging": False,
            "image_category": "watch_accessory",
        },
    },
}
